# Generated by Django 4.2.27 on 2025-12-08 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('occasion_type', models.CharField(choices=[('wedding', '💍 Wedding'), ('anniversary', '💞 Anniversary'), ('party', '🎉 Party'), ('other', '☕ Everyday / Other')], default='other', max_length=20)),
                ('category', models.CharField(blank=True, help_text='Display category, e.g. Chocolate, Kids, Vintage, Photo Cake.', max_length=100)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(help_text='Main cake image used on listing and detail pages.', upload_to='cakes/')),
                ('code', models.CharField(blank=True, help_text='Optional cake code / SKU shown on detail page.', max_length=30)),
                ('ingredients', models.TextField(blank=True, help_text='Ingredients list for the Ingredients & Allergy tab.')),
                ('allergy_advice', models.TextField(blank=True, help_text='Allergy & cross-contamination information.')),
                ('nutrition_info', models.TextField(blank=True, help_text='Nutritional information (per slice / per 100g).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CakeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Internal key, e.g. birthday, kids, chocolate.', max_length=30, unique=True)),
                ('label', models.CharField(help_text="Display name, e.g. 'Birthday Zone'.", max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Optional emoji icon, e.g. 🎂', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CakeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Displayed size label, e.g. 6" • serves 6–8', max_length=50)),
                ('serves_min', models.PositiveIntegerField(blank=True, null=True)),
                ('serves_max', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_default', models.BooleanField(default=False, help_text='Use this as the default size/price on the detail page.')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='cakes.cake')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('points_redeemed', models.PositiveIntegerField(default=0)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Money discount from redeemed points.', max_digits=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1 = poor, 5 = amazing')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Uncheck to hide this review from the website.')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cakes.cake')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='cakes.cake')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cakes.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='cakes.cakevariant')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cake',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Collections like Birthday Zone, Kids Collection, Chocolate Collection.', related_name='cakes', to='cakes.cakecollection'),
        ),
    ]
