# Generated by Django 4.2.27 on 2025-12-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_review_email_review_title_alter_review_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this review from the website.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 – Very poor'), (2, '2 – Poor'), (3, '3 – Okay'), (4, '4 – Good'), (5, '5 – Excellent')], help_text='1 = poor, 5 = amazing'),
        ),
    ]
